# -*- coding: utf-8 -*-
"""fast_app.ipnyb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RlKqQVaqkM9b5deAX9c1oKIdP3Sy10sQ
"""

from fastapi import FastAPI, File, UploadFile
import torch
from torchvision import transforms
from PIL import Image
import io

from fastapi.middleware.cors import CORSMiddleware      ''' important line'''

app = FastAPI()
app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],
            allow_credntials=True,
            allow_methods=["*"],
            allow_headers=["*"]
)

# -----------------------
# Load FULL saved model
# -----------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = torch.load("mnist_cnn_full_model.pth", map_location=device)
model.eval()

# -----------------------
# Image preprocessing (MNIST format)
# -----------------------
transform = transforms.Compose([
    transforms.Grayscale(num_output_channels=1),
    transforms.Resize((28, 28)),
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

# -----------------------
# Routes
# -----------------------
@app.get("/")
def root():
    return {"message": "MNIST model API is running"}

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    image_bytes = await file.read()
    image = Image.open(io.BytesIO(image_bytes))

    image = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(image)
        pred = torch.argmax(output, dim=1).item()

    return {"digit": int(pred)}